<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $excelData = [
            ['tarjeton' => '1045', 'nombres' => 'ACAXTENCO MORGADO JOSÉ', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '779', 'nombres' => 'ALMAZÁN BUSTAMANTE JOSÉ LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '370', 'nombres' => 'ALVAREZ HERNÁNDEZ MANUEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '448', 'nombres' => 'AMADOR JIMÉNEZ JOSUÉ', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '058', 'nombres' => 'ANAYA AVILÉS OSCAR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1061', 'nombres' => 'ANAYA MEJIA JULIO CÉSAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '955', 'nombres' => 'ANDRADE SÁNCHEZ MIGUEL ÁNGEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '939', 'nombres' => 'APODACA CORNELIO FRANCISCO JAVIER', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '919', 'nombres' => 'ARAGÓN GALVÁN ANGEL ROMAN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '456', 'nombres' => 'ARAGÓN LARIOS JORGE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1079', 'nombres' => 'ARELLANO GALVEZ GABRIEL TONATIUH', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '856', 'nombres' => 'ARENAS ESCAMILLA TONATIUH', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '745', 'nombres' => 'ARMAS ALVARADO OSCAR MARIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '556', 'nombres' => 'AVILÉS JUARICO MIGUEL ÁNGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '958', 'nombres' => 'BALDERAS DOMÍNGUEZ MARIA DE LA LUZ', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1050', 'nombres' => 'BAÑOS ZARCO EMILIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '039', 'nombres' => 'BARAJAS OLMOS GUSTAVO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1026', 'nombres' => 'BARRAZA ROMERO VICTORINO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1082', 'nombres' => 'BARRERA POZOS JORGE', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '763', 'nombres' => 'BARRERA REYES VICTOR MANUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '837', 'nombres' => 'BARRÓN GUERRERO VICTOR MANUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '883', 'nombres' => 'BAUTISTA ALMARAZ LUIS YAMIL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '005', 'nombres' => 'BAUTISTA BAUTISTA EFRAÍN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '854', 'nombres' => 'BAUTISTA GARCÍA JOSÉ', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '695', 'nombres' => 'BAUTISTA HERNÁNDEZ JOSÉ SANTIAGO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '927', 'nombres' => 'BAUTISTA SECUNDINO SAMUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '795', 'nombres' => 'BECERRIL OLVERA ELEAZAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1002', 'nombres' => 'BLANCAS LÓPEZ LEONARDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '969', 'nombres' => 'BOLAÑOS GARCÍA MIGUEL ANGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '550', 'nombres' => 'BOLAÑOS GÓMEZ EMMANUEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '116', 'nombres' => 'BOLAÑOS GÓMEZ LUIS ÁNGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '020', 'nombres' => 'BONILLA CABAÑAS ALEJANDRO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '775', 'nombres' => 'BRITO ESTRADA RAÚL ADÁN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '024', 'nombres' => 'CABAÑAS GARCÍA AGUSTÍN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '452', 'nombres' => 'CABRERA LAZCANO GUADALUPE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '946', 'nombres' => 'CABRERA RAMOS SERGIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '872', 'nombres' => 'CAMARGO VILLEDAS EDGAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '852', 'nombres' => 'CAMPOS CAMARENA FELIPE DE JESÚS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '907', 'nombres' => 'CAMPOS CERON RAYMUNDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1027', 'nombres' => 'CAMPOS HERNÁNDEZ JAIRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1033', 'nombres' => 'CAMPOS VAZQUEZ HUGO FERNANDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '913', 'nombres' => 'CANALES XICOTENCATL ALBERTO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1049', 'nombres' => 'CARMONA HERNÁNDEZ CRISTINA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1063', 'nombres' => 'CASTAÑEDA BAUTISTA LUIS YOVANI', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '956', 'nombres' => 'CASTAÑEDA CALVA FABIAN ANTONIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1085', 'nombres' => 'CASTILLO JAIME JUAN CARLOS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '019', 'nombres' => 'CASTILLO MARTÍNEZ MARIO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1051', 'nombres' => 'CAZARES BENITEZ GABRIEL RAFAEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '940', 'nombres' => 'CEBADA RIVERA JUAN CARLOS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '738', 'nombres' => 'CENOBIO QUIROZ MARCEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1073', 'nombres' => 'CENTENO TAVAREZ DIANA LAURA OLIVIA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '014', 'nombres' => 'CERON MORALES MATIAS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '117', 'nombres' => 'CERÓN ORDOÑEZ RODOLFO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1056', 'nombres' => 'CERVANTES PONCE IVÁN RAFAEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '417', 'nombres' => 'CHAPARRO RAMÍREZ JOSÉ JUAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '861', 'nombres' => 'CHIPOLINI DÁVALOS NORMA ANGELICA', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1041', 'nombres' => 'CLEMENTE SANCHEZ JOSÉ ALFREDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '948', 'nombres' => 'COLCHADO MARTÍNEZ ERWIN FROILAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '265', 'nombres' => 'CORONA VAZQUEZ HECTOR OSCAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '967', 'nombres' => 'CORTÉS GARCÍA PAULINO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '997', 'nombres' => 'CORTÉS LÓPEZ GABRIEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '970', 'nombres' => 'CORTÉS MONZALVO MANUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '649', 'nombres' => 'CORTÉS TOVAR ANDRÉS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1068', 'nombres' => 'CRUZ HERNÁNDEZ ALFONSO DE JESÚS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '172', 'nombres' => 'CRUZ HERNANDEZ ANGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '953', 'nombres' => 'CUELLAR CAMARGO RICARDO ISRAEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '726', 'nombres' => 'CUELLAR LEÓN RICARDO ISRAEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '113', 'nombres' => 'CURIEL SÁNCHEZ JOSÉ DANIEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '961', 'nombres' => 'DE LUCIO ESPINOSA FRANCISCO JAVIER', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1034', 'nombres' => 'DELGADILLO HUERTA ROBERTO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1047', 'nombres' => 'DIAZ DE LEON RIVERA ALFREDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '044', 'nombres' => 'DOLORES LÓPEZ ARTEMIO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '978', 'nombres' => 'DURÁN FLORES MARIANO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '971', 'nombres' => 'ENRIQUEZ CASIANO DANIEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '887', 'nombres' => 'ERNESTO SANDOVAL MARCO ANTONIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '794', 'nombres' => 'ESCAMILLA SOLIS OSWALDO DANIEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '983', 'nombres' => 'ESCORZA MARTÍNEZ VICTOR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '010', 'nombres' => 'ESCUDERO LARA JOEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '013', 'nombres' => 'ESPINOZA ORTIZ JULIO IVÁN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '920', 'nombres' => 'ESQUIVEL GARRIDO ALEJANDRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '968', 'nombres' => 'FIERROS VALLADARES JESÚS ABRAHAM', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '506', 'nombres' => 'FIGUEROA ARROYO LUIS ALBERTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '397', 'nombres' => 'FIGUEROA PASCUAL ANDRES', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1015', 'nombres' => 'FLORES ISLAS RICARDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '991', 'nombres' => 'FLORES MIRANDA ADRIÁN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '938', 'nombres' => 'FLORES MORENO ALFREDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '163', 'nombres' => 'FLORES SANCHEZ ARMANDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '184', 'nombres' => 'FUENTES LOPEZ JUAN JOSE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '036', 'nombres' => 'GARCÍA CANO ERNESTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '926', 'nombres' => 'GARCÍA HERNÁNDEZ ERNESTO ROGELIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1069', 'nombres' => 'GARCÍA ISLAS ANGEL DE JESÚS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '671', 'nombres' => 'GARCÍA LÓPEZ EDUARDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '934', 'nombres' => 'GARCÍA LÓPEZ MIGUEL ANGEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1087', 'nombres' => 'GARCÍA LORA VICTOR HUGO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '882', 'nombres' => 'GARCÍA MARTÍNEZ ANTONIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1006', 'nombres' => 'GARCÍA MARTÍNEZ LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '914', 'nombres' => 'GARCÍA MORALES CARLOS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1052', 'nombres' => 'GARCÍA OREYA GIL ARATH', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '876', 'nombres' => 'GARCÍA RIVERA EUSEBIO ARTURO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '933', 'nombres' => 'GARCÍA ROSALES RENÉ', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '126', 'nombres' => 'GARCÍA RUIZ JAVIER', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '097', 'nombres' => 'GARCÍA RUIZ JOSÉ LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1044', 'nombres' => 'GARCÍA SERRANO JOSÉ ISMAEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '899', 'nombres' => 'GARCÍA VARGAS EDGAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1005', 'nombres' => 'GONZÁLEZ BOBADILLA JUAN ALEJANDRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '941', 'nombres' => 'GONZÁLEZ CRUZ JUAN MANUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '706', 'nombres' => 'GONZÁLEZ ESCORIZA MIGUEL ANGEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '186', 'nombres' => 'GONZALEZ HERNANDEZ EDUARDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '790', 'nombres' => 'GONZÁLEZ SAMPAYO FILOMENA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1078', 'nombres' => 'GRANADOS CASTILLO FRANCISCO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1011', 'nombres' => 'GRANADOS LINARES ALFREDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1029', 'nombres' => 'GUERRERO JUÁREZ MARTIN EMILIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '999', 'nombres' => 'GUEVARA LEDEZMA ISIDRO EDGAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '057', 'nombres' => 'GUTIÉRREZ HIDALGO OSCAR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '100', 'nombres' => 'GUTIÉRREZ LUGO ARMANDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1036', 'nombres' => 'GUZMAN MARQUEZ LUIS ELIAS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1091', 'nombres' => 'GUZMAN SÁNCHEZ JOSÉ ROBERTO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '038', 'nombres' => 'HERNÁNDEZ ALCIBAR FRANCISCO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '021', 'nombres' => 'HERNÁNDEZ BOJORQUEZ GILBERTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '626', 'nombres' => 'HERNÁNDEZ GÓMEZ JOSÉ', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1023', 'nombres' => 'HERNÁNDEZ GONZÁLEZ JUAN CARLOS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '070', 'nombres' => 'HERNÁNDEZ JUÁREZ NICOLAS', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '356', 'nombres' => 'HERNANDEZ MARTINEZ JUAN RAFAEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1024', 'nombres' => 'HERNÁNDEZ MARTÍNEZ ROMAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '832', 'nombres' => 'HERNÁNDEZ OLVERA MANUEL ALEJANDRO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '944', 'nombres' => 'HERNÁNDEZ ORDUÑA ROBERTO JAVIER', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '881', 'nombres' => 'HERNÁNDEZ ORTA ISMAEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1010', 'nombres' => 'HERNÁNDEZ PEÑA JUAN CARLOS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '108', 'nombres' => 'HERNÁNDEZ PÉREZ ARTURO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1021', 'nombres' => 'HERNÁNDEZ PÉREZ SABINO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '123', 'nombres' => 'HERNÁNDEZ REYES JAVIER', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '902', 'nombres' => 'HERNÁNDEZ REYES JOEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1019', 'nombres' => 'HERNÁNDEZ REYES VICTOR JAVIER', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1066', 'nombres' => 'HERNÁNDEZ RODRIGUEZ ALAN RODRIGO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1022', 'nombres' => 'HERNÁNDEZ ROSALES ESTEBAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '947', 'nombres' => 'HERNÁNDEZ SIXTO JULIO CÉSAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '985', 'nombres' => 'HERNÁNDEZ TOLENTINO LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '943', 'nombres' => 'HERNÁNDEZ TORRES JOSÉ ARNULFO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '973', 'nombres' => 'HERNÁNDEZ TRANQUILINO HERMENEGILDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '821', 'nombres' => 'HERRERA ROMERO EDGAR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '129', 'nombres' => 'IBARRA PERALES ALFREDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '009', 'nombres' => 'ISLAS CASTRO GUILLERMO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '143', 'nombres' => 'ISLAS FLORES JOSÉ', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '735', 'nombres' => 'ISLAS GARCÍA ELISEO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1039', 'nombres' => 'ISLAS HERNÁNDEZ RICARDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '095', 'nombres' => 'ISLAS MENESES ELOY', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '915', 'nombres' => 'ISLAS MORALES NOHELIA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '534', 'nombres' => 'ISLAS PÉREZ FRANCISCO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '787', 'nombres' => 'JAEN ESPINOZA JOSÉ ALBERTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '715', 'nombres' => 'JAEN PEÑA UVALDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '768', 'nombres' => 'JARILLO GONZÁLEZ MARIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '962', 'nombres' => 'JIMATE GARCIA EDGAR JAFET', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '952', 'nombres' => 'JIMÉNEZ HERNÁNDEZ EDGAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '960', 'nombres' => 'JUÁREZ PERCASTRE KEVIN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1077', 'nombres' => 'JUÁREZ RODRIGUEZ ESTEBAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '602', 'nombres' => 'LABASTIDA GARCÍA ROBERTO ISRRAEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '188', 'nombres' => 'LANGO AVILES ISRAEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1080', 'nombres' => 'LANGO VARGAS HECTOR JAVIER', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '392', 'nombres' => 'LEAL ORTÍZ ALDO ISAAC', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '189', 'nombres' => 'LEON CARRILLO ENRIQUE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '002', 'nombres' => 'LEÓN ESQUIVEL REFUGIO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1067', 'nombres' => 'LEON ZARAZUA ALBERTO JAFET', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1058', 'nombres' => 'LICONA LOPEZ JOSÉ ALEJANDRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '873', 'nombres' => 'LÓPEZ FLORES HAERVY JAHIR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '974', 'nombres' => 'LÓPEZ FLORES RICARDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '515', 'nombres' => 'LÓPEZ GARCÍA LUIS FERNANDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1016', 'nombres' => 'LÓPEZ GARCÍA MICHEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1084', 'nombres' => 'LOPEZ LEMUS JOSÉ', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '684', 'nombres' => 'LÓPEZ MIRANDA SEVERIANO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '957', 'nombres' => 'LÓPEZ RODRÍGUEZ OMAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '820', 'nombres' => 'LORA MARTÍNEZ MARGARITA', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '629', 'nombres' => 'LOYDE MARTÍNEZ ROSALÍO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '383', 'nombres' => 'LOZADA PÉREZ MIGUEL ÁNGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '848', 'nombres' => 'LUCAS MARTÍNEZ MARIANO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1012', 'nombres' => 'MACIEL PATIÑO RAFAEL ANTONIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '942', 'nombres' => 'MADRIGAL AGUILERA ROGELIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '959', 'nombres' => 'MANILLA ROMERO JUAN MANUEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '846', 'nombres' => 'MANZANARES CHÁVEZ ERIK SAMAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1046', 'nombres' => 'MARRÓN RAMOS ABRAHAM', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1030', 'nombres' => 'MARTINEZ ARIAS GERONIMO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '084', 'nombres' => 'MARTÍNEZ ARISTA FERMIN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '998', 'nombres' => 'MARTÍNEZ DELGADO GERARDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '067', 'nombres' => 'MARTÍNEZ JIMÉNEZ ALEJANDRO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '909', 'nombres' => 'MARTÍNEZ MIGUEL FABIAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '267', 'nombres' => 'MARTINEZ MONTAÑO FLORENTINO ESMEREGILDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1070', 'nombres' => 'MARTÍNEZ PÉREZ ANGEL OSVALDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '737', 'nombres' => 'MARTÍNEZ VERONICA JULIAN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1032', 'nombres' => 'MAYA LONGORIA BRANDON JUSTIN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1031', 'nombres' => 'MAYA PEÑA JORGE', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '606', 'nombres' => 'MAYO RAMÍREZ JORGE ERNESTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '932', 'nombres' => 'MEDINA MARTÍN CECILIA GABRIELA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1009', 'nombres' => 'MEJIA BAUTISTA TANIA YANEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '092', 'nombres' => 'MEJÍA GÓMEZ GABINO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1008', 'nombres' => 'MEJIA ORTEGA MARIA GUADALUPE VIANET', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1088', 'nombres' => 'MENDOZA GONZÁLEZ YAIR DE JESÚS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1003', 'nombres' => 'MENDOZA MENÉSES RUBEN CUAUHTEMOC', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '903', 'nombres' => 'MERCADILLO CRUZ ALVARO ARTURO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '996', 'nombres' => 'MONROY SANTIAGO ADOLFO CÉSAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '191', 'nombres' => 'MONTALVO HERNANDEZ EUSEBIO ALEJANDRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '104', 'nombres' => 'MONTES DE OCA ISLAS OSCAR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '916', 'nombres' => 'MONZALVO CONTRERAS GUILLERMO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '045', 'nombres' => 'MONZALVO HERNÁNDEZ JAIME', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '061', 'nombres' => 'MONZALVO HERNÁNDEZ SANTIAGO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '054', 'nombres' => 'MONZALVO MORALES JUAN MANUEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '359', 'nombres' => 'MONZALVO REYES OSCAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '990', 'nombres' => 'MORA HERRERA ARTURO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '921', 'nombres' => 'MORA JOHN JAIRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1025', 'nombres' => 'MORALES ALMAGUER JOSÉ ABRAHAM', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1004', 'nombres' => 'MORALES ONESTO RODRIGO DE JESÚS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '542', 'nombres' => 'MORALES PÉREZ JOSÉ MARIA', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '851', 'nombres' => 'MORALES RODRÍGUEZ DIEGO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '977', 'nombres' => 'MORENO CASTILLO JESÚS ENRIQUE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '981', 'nombres' => 'MORENO FLORES LEONARDO DANIEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '884', 'nombres' => 'MORENO HERNÁNDEZ BRAYAN JESÚS', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '192', 'nombres' => 'MORENO OLVERA PATRICIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1035', 'nombres' => 'MUÑOZ CALVA CHRISTIAN IGNACIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '928', 'nombres' => 'MUÑOZ DANIEL JOSE LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '433', 'nombres' => 'NAJERA RAMÍREZ SALOMÓN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '178', 'nombres' => 'NARANJO RAMIREZ JOSE ENRIQUE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1037', 'nombres' => 'NAVARRO REYES FELIPE', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '069', 'nombres' => 'NIETO FLORES MIGUEL ÁNGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '132', 'nombres' => 'NIETO LÓPEZ NOÉ', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '080', 'nombres' => 'NORIEGA ORTEGA RAFAEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1064', 'nombres' => 'NUÑEZ LOPEZ OMAR ANTONIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1014', 'nombres' => 'OCHOA GUZMÁN MOISES', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '028', 'nombres' => 'OLIVARES MENDOZA ÁNGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '835', 'nombres' => 'OLVERA ANGELES ALVARO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1017', 'nombres' => 'OLVERA JUNCOS JORGE', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '592', 'nombres' => 'OLVERA RAMOS LUIS ALBERTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1020', 'nombres' => 'OMAÑA ANGELES JOEL LORENZO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '001', 'nombres' => 'ORAN AZPEITIA JÉSUS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1075', 'nombres' => 'ORDOÑEZ CARBALLIDO ENRIQUE', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '857', 'nombres' => 'ORTA HERNÁNDEZ JAVIER SAMUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '805', 'nombres' => 'ORTEGA HERNÁNDEZ JOSÉ ANDRÉS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '988', 'nombres' => 'ORTÍZ MARTÍNEZ CARLOS', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '646', 'nombres' => 'ORTIZ SEGURA FELIPE HUMBERTO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '029', 'nombres' => 'PADILLA GARCÍA ARMANDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '115', 'nombres' => 'PALACIOS DOMÍNGUEZ LEONARDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1083', 'nombres' => 'PALMA NUÑEZ JOSÉ ENRIQUE', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1007', 'nombres' => 'PALMA NUÑEZ LUIS MANUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '048', 'nombres' => 'PALOMINO HERNÁNDEZ JOSÉ ROBERTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1059', 'nombres' => 'PALOMO HERNÁNDEZ JOSÉ DAVID', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '925', 'nombres' => 'PAZ GÓMEZ RUTH ISABEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1072', 'nombres' => 'PEDRAZA GUADARRAMA AZAREEL ANTONIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '905', 'nombres' => 'PÉREZ ARROYO SALVADOR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '389', 'nombres' => 'PÉREZ BAÑOS PEDRO JAVIER', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '581', 'nombres' => 'PÉREZ BUTANDA FERNANDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '034', 'nombres' => 'PEREZ CASTAÑEDA TOMAS', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '046', 'nombres' => 'PÉREZ MARTÍNEZ JESÚS', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '087', 'nombres' => 'PÉREZ RUÍZ DAVID', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '270', 'nombres' => 'PÉREZ RUÍZ MELESIO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '908', 'nombres' => 'PÉREZ SÁNCHEZ FELICIANO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '889', 'nombres' => 'PÉREZ SÁNCHEZ MIGUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '929', 'nombres' => 'PÉREZ SERRANO ROMÁN DE JESÚS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '847', 'nombres' => 'QUESADA DE LOS SANTOS MARGARITA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '833', 'nombres' => 'QUIROGA GARCÍA EFRÉN ANSELMO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1065', 'nombres' => 'QUIROZ AGUIRRE VICTOR MANUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '101', 'nombres' => 'RAMÍREZ BARRAZA ÁNGEL GABRIEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '373', 'nombres' => 'RAMIREZ BARRAZA CLEMENTE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1060', 'nombres' => 'RAMIREZ ESTRADA JOSÉ LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '972', 'nombres' => 'RAMÍREZ MARTÍNEZ ULISES JAVIER', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '912', 'nombres' => 'RAMÍREZ SANTANDER JOSUÉ', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '966', 'nombres' => 'RAMOS LOZANO ALBERTO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1018', 'nombres' => 'RAYA ROBLES JAIME', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '897', 'nombres' => 'RECENDIZ CANTORAN ALDAIR', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '815', 'nombres' => 'REYES ARRIAGA NATANAEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1040', 'nombres' => 'REYES CHAVARRIA SERGIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '922', 'nombres' => 'REYES MERCADO JETSEHELIM', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1057', 'nombres' => 'REYES VILLEGAS JAIRZINO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '011', 'nombres' => 'RÍOS SALAS JORGE', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1090', 'nombres' => 'ROAN TORRES JOSÉ LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1042', 'nombres' => 'RODRIGUEZ GUERRERO LEONEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '896', 'nombres' => 'RODRÍGUEZ GUERRERO RAFAEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '107', 'nombres' => 'RODRÍGUEZ RECILLAS ALEJANDRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1089', 'nombres' => 'ROJAS RIOS EDGAR EDUARDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '923', 'nombres' => 'ROJAS ZAMORA MIGUEL ÁNGEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '725', 'nombres' => 'ROMERO ESPINOSA LUIS ÁNGEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1062', 'nombres' => 'ROMERO GUTIÉRREZ LUIS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '936', 'nombres' => 'ROMERO GUZMÁN LUIS FERNANDO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1071', 'nombres' => 'ROMERO HERNÁNDEZ ARTURO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '945', 'nombres' => 'RUVALCABA MARTÍNEZ PAOLA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '703', 'nombres' => 'SALINAS CERÓN ESTEBAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1038', 'nombres' => 'SALINAS JUÁREZ ALEJANDRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1054', 'nombres' => 'SAN JUAN ISLAS GUSTAVO IRVIN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1081', 'nombres' => 'SAN JUAN SANJUAN JESÚS MIGUEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '110', 'nombres' => 'SÁNCHEZ BAUTISTA ERNESTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '986', 'nombres' => 'SÁNCHEZ HERNÁNDEZ JULIO CÉSAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '800', 'nombres' => 'SÁNCHEZ LAZO LUIS EDUARDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '151', 'nombres' => 'SANCHEZ LEON JUAN MANUEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '911', 'nombres' => 'SÁNCHEZ LÓPEZ JUAN MARCOS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '984', 'nombres' => 'SÁNCHEZ MARTÍNEZ ANGEL GUSTAVO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '748', 'nombres' => 'SÁNCHEZ RAMÍREZ JOSEFINA', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '364', 'nombres' => 'SÁNCHEZ ROMERO SERGIO RAÚL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '052', 'nombres' => 'SÁNCHEZ UBALDO JUAN GERMÁN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1043', 'nombres' => 'SANTILLAN HERNÁNDEZ ADRIAN', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '098', 'nombres' => 'SANTILLÁN SANTILLÁN JUAN CARLOS', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '008', 'nombres' => 'SANTILLAN VÁZQUEZ GLADIS', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '517', 'nombres' => 'SEGURA ROBLES EDGAR ADÁN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '917', 'nombres' => 'SILVA LÓPEZ DAVID', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '707', 'nombres' => 'SOTO AMADOR JOSÉ MANUEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '802', 'nombres' => 'TÉLLEZ CERÓN SAÚL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '530', 'nombres' => 'TÉLLEZ GIRÓN ZENIL JUAN ALBERTO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1086', 'nombres' => 'TOLEDO CHAZARO SAJID JOSHUA', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1028', 'nombres' => 'TORRES DIAZ NEDIKER', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1076', 'nombres' => 'TORRES DOMÍNGUEZ ERNESTO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '463', 'nombres' => 'TORRES MORENO MIGUEL ÁNGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1055', 'nombres' => 'TREJO PÉREZ GUSTAVO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '068', 'nombres' => 'TRUJILLO ALVARADO LUIS PABLO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '994', 'nombres' => 'TURLAY SÁNCHEZ ALEXIS ALBERTO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '194', 'nombres' => 'VALDON LARA MARYAVIT', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '077', 'nombres' => 'VALENCIA DORANTES JOAQUIN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '954', 'nombres' => 'VALENCIA ISLAS NESTOR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '982', 'nombres' => 'VALENCIA VERA ISAAC', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '976', 'nombres' => 'VÁZQUEZ AGUILAR MARTIN', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '1053', 'nombres' => 'VÁZQUEZ ARTEAGA GUILLERMO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '845', 'nombres' => 'VÁZQUEZ PÉREZ ÁNGEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '931', 'nombres' => 'VÁZQUEZ ZAMORA LUIS OCTAVIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '718', 'nombres' => 'VEGA MÁRQUEZ JOSÉ DANIEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '401', 'nombres' => 'VEGA QUIJANO VICTOR GABRIEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '421', 'nombres' => 'VELÁZQUEZ ESCALANTE CARLOS GERARDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '476', 'nombres' => 'VERA NERI ROSALIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '134', 'nombres' => 'VILLAFUERTE TREJO SERGIO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '951', 'nombres' => 'VILLANUEVA DOMINGUEZ JOSÉ ANGEL', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '844', 'nombres' => 'VIVEROS GARCÍA DANIEL', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '165', 'nombres' => 'ZAMORA VARGAS EDGAR RICARDO', 'tipo_tarjeton' => 'C'],
            ['tarjeton' => '680', 'nombres' => 'ZAMORA ZAMORA ALVARO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '1074', 'nombres' => 'ZAPATA CHÁVEZ ELEAZAR', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '992', 'nombres' => 'ZAVALA ÁLVAREZ JOSÉ ELIAS', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '930', 'nombres' => 'ZAVALA DELGADILLO MARCO ANTONIO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '886', 'nombres' => 'ZUÑIGA HERMOSILLO MANUEL ALEJANDRO', 'tipo_tarjeton' => 'B'],
            ['tarjeton' => '086', 'nombres' => 'ZUÑIGA OLMOS OSCAR ANDRÉS', 'tipo_tarjeton' => 'C'],
        ];

        DB::beginTransaction();

        try {
            $dbConductores = DB::table('conductores')->get();
            
            $dbMap = [];
            foreach ($dbConductores as $c) {
                $name = trim(mb_strtolower($c->nombres));
                $name = str_replace(['á','é','í','ó','ú','ñ'], ['a','e','i','o','u','n'], $name);
                $dbMap[$name] = $c;
            }

            foreach ($dbConductores as $c) {
                $tarjeton_libre = $c->tarjeton;
                if (strpos($tarjeton_libre, '_BAJA_') === false) {
                    $tarjeton_libre = $tarjeton_libre . '_BAJA_' . $c->id;
                }
                
                DB::table('conductores')->where('id', $c->id)->update([
                    'estatus' => 'baja',
                    'tarjeton' => $tarjeton_libre,
                    'updated_at' => now()
                ]);
            }

            foreach ($excelData as $row) {
                $excelNameRaw = trim($row['nombres']);
                $nameKey = trim(mb_strtolower($excelNameRaw));
                $nameKey = str_replace(['á','é','í','ó','ú','ñ'], ['a','e','i','o','u','n'], $nameKey);
                
                $tarjeton = $row['tarjeton'];
                $tipo = $row['tipo_tarjeton'];
                
                if (isset($dbMap[$nameKey])) {
                    $c = $dbMap[$nameKey];
                    DB::table('conductores')->where('id', $c->id)->update([
                        'nombres' => $excelNameRaw,
                        'tarjeton' => $tarjeton,
                        'tipo_tarjeton' => $tipo,
                        'estatus' => 'activo',
                        'estado_servicio' => 'disponible',
                        'updated_at' => now()
                    ]);
                } else {
                    DB::table('conductores')->insert([
                        'nombres' => $excelNameRaw,
                        'apellidos' => '',
                        'tarjeton' => $tarjeton,
                        'tipo_tarjeton' => $tipo,
                        'estatus' => 'activo',
                        'estado_servicio' => 'disponible',
                        'created_at' => now(),
                        'updated_at' => now()
                    ]);
                }
            }
            
            DB::commit();
            
        } catch (\Exception $e) {
            DB::rollBack();
            throw $e;
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // No down migration provided for this massive sync
    }
};
